name: 'ESP32 builder with ESP-IDF v4.1'
description: 'GitHub Action to build your ESP32 code with Espressif IoT Development Framework v4.1'
inputs:
  src-directory:
    description: 'The directory with source code'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/prepare.sh
      shell: bash
    - run: ${{ github.action_path }}/build.sh ${{ inputs.src-directory }}
      shell: bash
